export const INIT_COMMENTS = 'INIT_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const MODIFY_COMMENT = 'MODIFY_COMMENT';

export const FETCH_DRAFTS = 'FETCH_DRAFTS';
export const RECEIVE_DRAFTS = 'RECEIVE_DRAFTS';